Manage media
JustAnOtherCoder13/RealEstateManager pull request #7
Opened 2021-01-08 09:29 UTC by JustAnOtherCoder13

add media when save or update property work well

how could i make AddPropertyFragment lighter?

2021-01-08 15:20 UTC, fodeguirassy requested changes

2021-01-08 15:20 UTC, fodeguirassy commented on app/src/main/java/com/openclassrooms/realestatemanager/presentation/utils/ManageImageHelper.java
> +                imageFileName,
use png

2021-01-08 15:20 UTC, fodeguirassy commented on app/src/main/java/com/openclassrooms/realestatemanager/presentation/utils/ManageImageHelper.java
> +        } catch (IOException ex) {
toast error

2021-01-09 08:45 UTC, JustAnOtherCoder13 commented on app/src/main/java/com/openclassrooms/realestatemanager/presentation/utils/ManageImageHelper.java
> +                imageFileName,
done

2021-01-09 08:47 UTC, JustAnOtherCoder13 commented on app/src/main/java/com/openclassrooms/realestatemanager/presentation/utils/ManageImageHelper.java
> +        } catch (IOException ex) {
done

2021-01-10 17:53 UTC, JustAnOtherCoder13 commented
some little bug to fix, on returned media list, will certainly be ok tomorow

2021-01-11 16:34 UTC, fodeguirassy approved these changes

2021-01-11 16:34 UTC, merged